### ISSUE TITLE
Fails to launch the realsense file

### ISSUE THREAD

**Issue by Oburshan** [engcang/rovio-application#1]
I get this massage when launching rs_camera.launch:

RLException: unused args [infra2_width, infra1_fps, infra2_fps, infra1_width, enable_imu, infra2_height, infra1_height] for include of [/opt/ros/melodic/share/realsense2_camera/launch/includes/nodelet.launch.xml]

**Thanks!**

**Comment by engcang** [comment]
Hi @Oburshan. I am so sorry for being late.
It seems that the version of realsense ROS package is the problem.
I recommend to install realsense ROS package not by `sudo apt install` but manually build yourself.

Please refer my other repo here: https://github.com/engcang/VINS-application/tree/Intel-D435i
1. Download the latest SDK and build it,
2. Download the latest realsense ROS package (should be compatible with the SDK version above) and build it

thanks
